python train_transformer.py     --model_dim=512\
                                --num_heads=8 \
                                --num_encoder_layers=1 \
                                --num_decoder_layers=1 \
                                --output_window=96 \
                                --batch_size=8\
                                --num_epochs=10 \
                                --learning_rate=1e-4\
                                --train_data_path="data/train_data.csv" \
                                --val_data_path="data/val_data.csv" \
                                --save_path="save/transformer/" \
                                --model_suffix="96_{i}" \
                                --gpu=1 \
                                --seed=42

python test_transformer.py      --model_dim=512 \
                                --num_heads=8 \
                                --num_encoder_layers=1 \
                                --num_decoder_layers=1 \
                                --output_window=96 \
                                --batch_size=64 \
                                --test_data_path="data/original/test_data.csv" \
                                --train_data_path="data/train_data.csv" \
                                --model_path="save/transformer/transformer_model_best_96_{i}.pth" \
                                --gpu=1 \
                                --seed=42 \
                                --save_csv_path="results/transformer/test_results_96_{i}.npy" \
                                --save_plot_path="results/transformer/predictions_vs_targets_96_{i}.png" \
                                --seed=42